version: "3"
services:
  mysql8:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      # 设置初始化脚本：
      # 执行./script/mysql/ 文件中的对应sql语句
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      # 映射 13316 端口:
      # 外部访问用13316
      - "13316:3306"