test:
  key: value

redis:
  addr: "localhost:6379"

db:
  src:
    dsn: "root:123456@tcp(localhost:13316)/webook"
  dst:
    dsn: "root:123456@tcp(localhost:13316)/webook_intr"

kafka:
  addr:
    - "localhost:9094"

grpc:
  server:
    etcdAddr: "localhost:12379"
    port: 8090
    name: "interactive"


migrator:
  http:
    addr: "localhost:8082"