test:
  key: value

redis:
  addr: "localhost:6379"

db:
  dsn: "root:123456@tcp(localhost:13316)/webook"

kafka:
  addr:
    - "localhost:9094"

etcd:
  addrs:
    - "localhost:12379"


grpc:
  client:
    intr:
      addr: "etcd:///service/interactive"

